#!/bin/bash
#
# pcrate driver startup      This is a startup script for use in /etc/init.d 
# 
# description:  Start up custom gbit drivers for CMS/EMU Peripheral Crates  
#
#-------------------------------------------------------------------------

# Source function library.
. /etc/rc.d/init.d/functions

PROG=$"Peripheral Crate Gbit driver"
KERNELVERSION=`/bin/uname -r`
PCRATEDRIVERLIB=/lib/modules/${KERNELVERSION}/kernel/drivers/net
PCRATEPROCFILE=/proc/sys/dev/schar/0
PCRATELOCKFILE=/var/lock/subsys/pcratedriver


case "$1" in     
start) 
   echo  $"Starting $PROG: "
   [ -f $PCRATELOCKFILE ]  && (echo -n "stale lock file, driver not properly stopped"; warning; echo)
   # look for default (pre-loaded) sky2 modules and remove it.
   # (this only applies after a cold start)
   /bin/grep -q sky2 /proc/modules
   if [ "$?" = "0" ]; then 
     rmmod sky2; echo -n "cleaning up old sky2"; warning; echo
   fi
   # 
   $0 recreate
   action "eth_hook" /sbin/modprobe eth_hook
   action "sky2" /sbin/modprobe sky2 copybreak=5000 
   action "eth1" /sbin/ifconfig eth1 up
   touch $PCRATELOCKFILE
  ;;		
stop)
  echo  $"Stopping $PROG: "
  [ -f $PCRATELOCKFILE ]  || (echo -n "no lock file, driver not properly started"; warning; echo)
  action "eth1" /sbin/ifdown eth1
  action "sky2" /sbin/rmmod sky2
  action "eth_hook" /sbin/rmmod eth_hook
  rm -f $PCRATELOCKFILE
  ;; 		
restart)
  # Reload Gbit drivers
  $0 stop
  $0 start
  ;; 				
condrestart)
  if [ -f /var/lock/subsys/pcratedriver ]; then
    $0 stop
    $0 start
  fi
  ;;
status)     	   
  echo  $"Status $PROG: "
  echo "--- /proc/modules:"
  /bin/grep sky2 /proc/modules || echo "none"
  echo "--- $PCRATEPROCFILE:"
  [ -f  $PCRATEPROCFILE ] && /bin/cat $PCRATEPROCFILE || echo "none"
  ;;
recreate)
   # recreate schar device and make writable for group csc
   echo $"Recreating $PROG (schar device): "
   [ -c /dev/schar ] || (echo -n "device not present or bad"; warning; echo)
   /bin/rm -f /dev/schar
   /bin/mknod /dev/schar c 42 0
   /bin/chgrp cscdev /dev/schar
   /bin/chmod ug+rw /dev/schar
   # the next two lines should be removed ...
   /bin/chmod ugo+rwx /dev/schar
   cd /dev; /bin/ln -sf schar schar1
   # 
   echo -n "/dev/schar recreated"
   [ -c /dev/schar ] && success || failure
   echo
   ;;
*)
  /bin/echo $"Usage $0 {start|stop|restart|condrestart|recreate|status}"
  exit 1
esac
